eureka:
  client:
    service-url:
      defaultZone: "http://admin:admin@localhost:8761/eureka/"
kafka:
  agentMessageTopic: "AGENT_MESSAGE_TOPIC"
  bootstrap-servers: "localhost:9092"
  callMessageTopic: "CALL_MESSAGE_TOPIC"
  generalMessageTopic: "GENERAL_MESSAGE_TOPIC"
server:
  port: 26084
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
  datasource:
    password: "{cipher}218f3f1bf6fe974e21eac3d98bc50c1ae67af65e9becd01dc7215c4627a97e39"
    url: "jdbc:sqlserver://localhost:1433;database=EventServer;encrypt=false"
    username: "{cipher}97b4d20cd2c95728baef0fbb5a85a78e473519a1ae92bf6057e19452aa3f70b8"
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: "https://sistas-keycloak.sistas.com.tr/realms/sistas"
        registration:
          oidc:
            client-id: "chatbot"
            client-secret: "{cipher}3ad547c5cc069626912b67cb1c426d1998e2d9b8a164e14a4e2377418fff6b5e961c1ddd81815cec1e9ccdf9000ed15fe068c4a427457bf66e906ebb9e8dfb0b"
