application:
  auto-sign:
    enabled: false
    redirect-url: "https://google.com"
  external-project-redirect-properties[0]:
    name: "CC"
    url: "http://127.0.0.1:9999"
  external-project-redirect-properties[1]:
    name: "EVA"
    url: "http://127.0.0.1:9090"
  hazelcast:
    port: 5701
  keycloak-admin:
    app-realm-id: "sistas"
    app-resource-id: "sistas-voice"
    app-resource-secret: "{cipher}e7dc9ad94f1d44997e4fb7963ba69a7503963e324a8ba6c267a0fbc48722c02df56ed308493ac95c94c53d46fc85271dc21f8638ef067fb774e01ccc64bbe916"
    client-id: "admin-cli"
    max-pool-size: 10
    password: "{cipher}44536e1c8bc12d8555201668598a37738aa2601836f7c552cef687e9840a697e"
    realm: "master"
    server-url: "https://sistas-keycloak.sistas.com.tr"
    trusted-audiences:
    - "sistas-eva"
    - "smart"
    - "campus"
    - "sistas-phone"
    - "chatbot"
    - "client_credentials"
    username: "{cipher}27ecb2fd2285e3b9c869829855bdbeaa97ddc0094e3ceebfe53623cbd93e0bde"
  session-management-properties:
    concurrent-session-allowed: false
    session-timeout-in-minutes: 120
eureka:
  client:
    service-url:
      defaultZone: "http://admin:admin@localhost:8761/eureka/"
jhipster:
  gateway:
    rate-limiting:
      duration-in-seconds: 3600
      enabled: false
      limit: 100000
server:
  port: 8080
spring:
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 1000
  hazelcast:
    network:
      join:
        tcp-ip:
          members:
          - "127.0.0.1:5050"
          - "127.0.0.1:5051"
